name: words
description: Demonstrates how to use the record plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  path_provider: ^2.0.2
  just_audio: ^0.9.5

  flutter:
    sdk: flutter
  #firebase_image: ^1.0.1
  firebase_image:
    git:
      url: git://github.com/blinkin/firebase_image.git
      ref: issue37_fix
  record: ^3.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  fluttertoast: ^8.0.8
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  rflutter_alert: ^2.0.4
  lottie: ^1.1.0
  circular_countdown_timer: ^0.2.0
  animated_button: ^0.2.0
  flutter_svg: ^0.22.0
  get: ^4.3.5
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.9
  audioplayers: ^0.18.0

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotte/
    - assets/stop_msc/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf
        
  uses-material-design: true
